name: Deploy app on EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    steps:
        - uses: shivammathur/setup-php@main
          with:
            php-version: '8.3'
        - uses: actions/checkout@v4

        - name: executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: 13.233.104.206
            username: ec2-user
            key: ${{ secrets.SSH_KEY }}
            port: 22
            script: whoami